### ISSUE TITLE
Strange encoding name UTF8

### ISSUE THREAD

**Issue by martin-g** [sksamuel/pulsar4s#1]
Hi,

I was looking at the code and noticed strange encoding name used at https://github.com/sksamuel/pulsar4s/blob/2e16f517ddf4ed03344d1220636b9bd86e004015/pulsar4s-circe/src/main/scala/com/sksamuel/pulsar4s/circe/package.scala#L30
The (usual) name is `UTF-8` while in the code it is `UTF8	` (without the dash).
Maybe Java handles it somehow, since the tests pass but I think it would be better to use `new String(bytes, StandardCharsets.UTF8)` instead.

**Comment by martin-g** [comment]
Same at https://github.com/sksamuel/pulsar4s/blob/2e16f517ddf4ed03344d1220636b9bd86e004015/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/Producer.scala#L18

**Comment by sksamuel** [comment]
UTF8 can be used as it's an alias in the JDK. See sun.nio.cs.StandardCharsets line 13.

But you're right, I should be using a constant instead of a string so I've changed it and released 0.90.2
