### ISSUE TITLE
Any plans to support Batch Recieve

### ISSUE THREAD

**Issue by ckmcd** [sksamuel/pulsar4s#209]
Hi Folks.  I was just looking for clarity on whether or not there are any plans to support batch receive.   I noticed that #158 was closed without addressing the issue.

Thanks

**Comment by gmethvin** [comment]
I think we should add support and would personally welcome a contribution to add that functionality. I think that issue might've been accidentally closed by @sksamuel ?

**Comment by sksamuel** [comment]
Yes I have no idea why I closed that, sorry.

**Comment by gmethvin** [comment]
I'll go ahead and close this since the original issue is #158. @ckmcd were you interested in submitting a PR for this? If not I can take a stab at it when I get some free time.
