### ISSUE TITLE
Implicit schema not found when using play-json

### ISSUE THREAD

**Issue by iam-nagarajan** [sksamuel/pulsar4s#217]
I am trying to produce a message with json schema, and already playjson used in the project. So imported the package as recommended in the doc for implicit schema, but I am getting the error 

> could not find implicit value for evidence parameter of type org.apache.pulsar.client.api.Schema[com.thoughtworks.iot_api.ActivityData]
> Error occurred in an application involving default arguments.
>   var producer = client.producer[ActivityData](ProducerConfig(topic))

Code used:
```
import com.sksamuel.pulsar4s.{ProducerConfig, PulsarClient, Topic}
import com.sksamuel.pulsar4s.playjson._

case class ActivityData(activityType: String, timeStamp: String)

object SchemaTest extends App {
  var client = PulsarClient("pulsar://localhost:6650")
  var topic = Topic("activity_new")
  var producer = client.producer[ActivityData](ProducerConfig(topic))

  producer.send(ActivityData("Motion", "1596448394224"))

  producer.close()
  client.close()
}
```

**Comment by gmethvin** [comment]
This is expected behavior given your current code. You need an implicit `Format` in scope for `ActivityData` to generate the schema. It doesn't generate one for you automatically.
