### ISSUE TITLE
The receive() function cannot receive a message until the seek() function is called

### ISSUE THREAD

**Issue by hellozepp** [sksamuel/pulsar4s#57]
I find that if I don't call `seek(messageId: MessageId): Unit` or `consumer.seekEarliest()` , `consumption,consumer.receive()` will block.

My scala tests are as follows:

    val client = PulsarClient("pulsar://localhost:6650")
    val topic = Topic("persistent://sample/standalone/ns1/test_" + UUID.randomUUID)

    val producer = client.producer(ProducerConfig(topic))
    val messageId = producer.send("wibble")
    producer.send("wobble")
    producer.send("wubble")
    producer.close()

    var consumer = client.consumer(ConsumerConfig(topics = Seq(topic), subscriptionName = Subscription.generate,
      subscriptionType = Some(SubscriptionType.Exclusive)
    ))
    consumer.seek(messageId.get)
    var msg = consumer.receive
    new String(msg.get.data) shouldBe "wibble"
    consumer.acknowledge(msg.get)
    consumer.close()

    consumer = client.consumer(ConsumerConfig(topics = Seq(topic), subscriptionName = Subscription.generate,
      subscriptionType = Some(SubscriptionType.Exclusive)
    ))
    consumer.seek(messageId.get)
    msg = consumer.receive
    new String(msg.get.data) shouldBe "wibble"
    consumer.close()
    client.close()
 
 Is this the right way to do it ?

**Comment by sksamuel** [comment]
In those examples, the messages are sent first, so you need to seek earliest in order to go back to before the messages were sent.

**Comment by gmethvin** [comment]
If you seek to a message id, the next message to be received will be the *next* message after that message on the topic. So this behavior is not a bug.
