### ISSUE TITLE
AckTimeout should be exposed as a parameter to ConsumerConfig

### ISSUE THREAD

**Issue by hellozepp** [sksamuel/pulsar4s#58]
**Describe the bug**
When I tried to wait for a timeout to trigger the `redeliver` mechanism, I found that no `ackTimeout` parameter could be set, and I thought I could expose a parameter.

**Comment by gmethvin** [comment]
This is implemented now https://github.com/sksamuel/pulsar4s/blob/19e88e1838cb29aaf51263da6af3cf99e7b2b212/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/ProducerConfig.scala#L41
