### ISSUE TITLE
Support for regex subscriptions

### ISSUE THREAD

**Issue by gmethvin** [sksamuel/pulsar4s#7]
The Java client allows you to subscribe to multiple topics using a pattern like

```scala
Pattern allTopicsInNamespace = Pattern.compile("persistent://public/default/.*");
Consumer allTopicsConsumer = consumerBuilder.topicsPattern(allTopicsInNamespace).subscribe();
```

It should be possible to provide a Scala interface to achieve this using a `Regex` for the pattern.

**Comment by sksamuel** [comment]
Quite right, that's quite an omission actually.

**Comment by sksamuel** [comment]
I've added support for this but cannot get the tests to pass currently. Baffling.

**Comment by sksamuel** [comment]
Tests sorted. 2.1.2 released with topic patterns support. Slight tweak to the order of params in the consumer.
